import jsPDF from 'jspdf';
import 'jspdf-autotable';
import type { ApiDetectionResponse } from '@/services/api';
import { getDetectionImage } from './detectionImages';

export function generatePdfReport(result: ApiDetectionResponse, uploadedImageUrl?: string | null) {
  const doc = new jsPDF();
  const { analysis, location, timestamp, detection_id } = result;

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(16, 185, 129);
  doc.setFontSize(22);
  doc.text('SATGUARD', 14, 20);
  doc.setFontSize(10);
  doc.setTextColor(200, 200, 200);
  doc.text('AI-Powered Illegal Mining Detection Report', 14, 28);
  doc.text(`Report ID: ${detection_id || 'N/A'}`, 14, 34);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 120, 34);

  let y = 50;

  // Detection Summary
  doc.setTextColor(0);
  doc.setFontSize(14);
  doc.text('Detection Summary', 14, y);
  y += 8;

  const summaryData = [
    ['Mining Detected', result.mining_detected ? 'YES' : 'NO'],
    ['Confidence', `${result.confidence.toFixed(1)}%`],
    ['Severity', analysis.severity],
    ['Location', location.name],
    ['Coordinates', `${location.latitude}°N, ${location.longitude}°E`],
    ['Timestamp', new Date(timestamp).toLocaleString()],
    ['Area Affected', `${analysis.estimatedAreaHectares.toFixed(2)} hectares`],
    ['Estimated Loss', `$${analysis.estimatedLossUSD.toLocaleString()}`],
    ['Machinery Count', String(analysis.machineryCount)],
  ];

  (doc as any).autoTable({
    startY: y,
    head: [['Parameter', 'Value']],
    body: summaryData,
    theme: 'striped',
    headStyles: { fillColor: [16, 185, 129] },
    margin: { left: 14, right: 14 },
  });

  y = (doc as any).lastAutoTable.finalY + 12;

  // AI Reasoning
  doc.setFontSize(14);
  doc.text('AI Analysis', 14, y);
  y += 8;
  doc.setFontSize(10);

  const addWrappedText = (label: string, text: string) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 14, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(text, 180);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 6;
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
  };

  addWrappedText('Reasoning:', analysis.reasoning);
  addWrappedText('Environmental Impact:', analysis.environmentalImpact);
  addWrappedText('Legal Context:', analysis.legalContext);

  // Try to add the uploaded image
  const imgData = uploadedImageUrl || (detection_id ? getDetectionImage(detection_id) : null);
  if (imgData) {
    if (y > 160) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(14);
    doc.text('Satellite Image Evidence', 14, y);
    y += 8;
    try {
      doc.addImage(imgData, 'JPEG', 14, y, 120, 80);
      y += 85;
    } catch {
      // Image format not supported — skip
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('This report was generated by SATGUARD - AI-Powered Illegal Mining Detection System', 14, 285);
  doc.text('Confidential - For authorized personnel only', 14, 290);

  doc.save(`SATGUARD_Report_${detection_id || 'unknown'}_${new Date().toISOString().slice(0, 10)}.pdf`);
}
